s4_project/config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => "admin#index"
  resources :orders
  get 'store', to: 'store#index', :as => 'store'

  resources :line_items
  resources :carts
  resources :categories
  get "log_out" => "session#destroy", :as => "log_out"
  get "log_in" => "session#new", :as => "log_in"
  
  get "sign_up" => "users#new", :as => "sign_up"
  post   'log_in'   => 'session#create'
 root 'store#index'
get 'products', to: 'products#index',:as => 'products'
 get 'products/new', to: 'products#new',:as => 'new_products'
get 'products/:id', to: 'products#show',:as => 'product'
post 'products', to: 'products#create'
get 'products/:id/edit', to: 'products#edit',:as => 'edit_product' 
patch 'products/:id', to: 'products#update'
delete 'products/:id',  to:   'products#destroy'
  resources :users

end

s4_project/app/models/product.rb
class Product < ActiveRecord::Base
	
belongs_to :category
has_many :line_items
has_many :orders, through: :line_items
before_destroy :ensure_not_referenced_by_any_line_item
	validates :name,:price,:quantity,presence: true

validates :price,numericality:{greater_than_or_equal_to:0.01}
validates :quantity,numericality: {only_integer: true}

private
def ensure_not_referenced_by_any_line_item
  if line_items.empty?
    return true
else
   errors.add(:base,'Line Items present')
	return false
end

end

end

s4_project/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_filter :authorize
  before_action :set_product, only: [:show, :edit, :update, :destroy]
before_action :set_categories, only: [:new, :edit]
before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
     @product = Product.find(params[:id]) 
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
     @product = Product.find(params[:id]) 
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
 def set_categories
      @categories = Category.order(:cname)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image_file, :quantity)
    end
end

s4_project/app/helpers/products_helper.rb
module ProductsHelper
end

s4_project/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_file %><br>
    <%= f.text_field :image_file %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div>
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, @categories, :id, :cname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

s4_project/app/views/products/_product.html.erb
<section>

  <h3><%= link_to product.name,product%></h3>
<p><%=product.description %></p>
  
  <div class="product">
 
 
  
  <% if product.image_file %>
    <p><%= image_tag product.image_file,:width => '200' %></p>
  <% end %>
  
  <p>
    <%= product.description %>
  </p>
  
  <p>
    <strong>Price:</strong>
    <%= number_to_currency(product.price) %>
  </p>
  <% if product.category %>
    <p>Category: <%= product.category.cname %></p>
  <% end %>
  

  
</div>
</section>

s4_project/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

s4_project/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>
  <% if session[:user_id] %>

   <h4 class="opt"> <%= link_to 'Orders', orders_path %>
   <%= link_to 'Products', products_path %>
   <%= link_to 'Users', users_path %></h4>
   <h4 class="new1"><%= link_to 'New Product', new_products_path %></h4>

 <% end %> 

<% @products.each do |product| %>

 <%=render product%>
 <%= link_to 'Show', product %>
<%if current_user.try (:admin?)%>
    
  <%= link_to 'Edit', edit_product_path(product) %>
<p><%= link_to 'Destroy',product , method: :delete, data: { confirm: 'Are you sure?' } %></p>
<%else%>
<%= link_to "back", root_path %>
<%end%>
<%=button_to'Add to Cart',line_items_path(product_id: product)
%>
 
<%end%>

s4_project/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render partial:'form' %>

<%= link_to 'Back', products_path %>

s4_project/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p> -->
 <%=render @product%> 

<!-- <h3><%=@product.name %></h3>
<p><%=@product.description %></p>
<%= image_tag @product.image_file %> -->
 <p><%= link_to "Home",root_path%></p>
<%if current_user.try (:admin?)%>
<%= link_to 'Edit', edit_product_path(@product) %> 

<%= link_to 'Back', products_path %>
<%end%>