s4_project/config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => "admin#index"
  resources :orders
  get 'store', to: 'store#index', :as => 'store'

  resources :line_items
  resources :carts
  resources :categories
  get "log_out" => "session#destroy", :as => "log_out"
  get "log_in" => "session#new", :as => "log_in"
  
  get "sign_up" => "users#new", :as => "sign_up"
  post   'log_in'   => 'session#create'
 root 'store#index'
get 'products', to: 'products#index',:as => 'products'
 get 'products/new', to: 'products#new',:as => 'new_products'
get 'products/:id', to: 'products#show',:as => 'product'
post 'products', to: 'products#create'
get 'products/:id/edit', to: 'products#edit',:as => 'edit_product' 
patch 'products/:id', to: 'products#update'
delete 'products/:id',  to:   'products#destroy'
  resources :users

end

s4_project/app/models/cart.rb
class Cart < ActiveRecord::Base
belongs_to :user
	has_many :line_items,dependent: :destroy

def add_product(product_id)
current_item = line_items.find_by_product_id(product_id)
if current_item
current_item.quantity += 1
else
current_item=line_items.build(product_id: product_id)
end
current_item
end
def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

s4_project/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
skip_before_filter :authorize, only:[:create,:update,:destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
begin

@cart =Cart.find(params[:id])
rescue ActiveRecord::RecordNotFound

logger.error "Attempt to access invalid cart #{params[:id]}"
redirect_to store_url,
notice: 'Invalidcart'

else

respond_to do |format|
format.html
format.json {render json:@cart}
end
end
end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy

 @cart=current_cart
 @cart.destroy
session[:cart_id]=nil
respond_to do|format|
  format.html{ redirect_to store_path,
  notice: 'Your cart is currently empty'}

format.json{head :no_content}
end
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

s4_project/app/helpers/carts_helper.rb
module CartsHelper
end

s4_project/app/views/carts/_cart.html.erb
<div class="cart_title">My Cart </div>
<table>
<%= render(cart.line_items) %>
<tr class="total_line">
<td colspan="2">Total</td>

<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
</tr>
</table>
<%= button_to "Checkout", new_order_path, method: :get %> 

s4_project/app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

s4_project/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

s4_project/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>

      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Cart', new_cart_path %>

s4_project/app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

s4_project/app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="cart_title"> my cart </div>

<table>
<%@cart.line_items.each do |item| %>
<tr>
<td><%= item.quantity %> &times;</td>
<td><%=item.product.name%></td>
<td class="item_price">
<%=number_to_currency(item.total_price)%>
</td>
</tr>
<%end%>
<tr class="total_line">
<td colspan="2">Total</td>
<td class="total_cell">
<%=number_to_currency(@cart.total_price)%>
</td>
</tr>
</table>


<%=button_to 'Empty cart',@cart,method: :delete,confirm:'Are you sure?'%>
<%= button_to "Checkout", new_order_path, method: :get %> 
<%if current_user.try (:admin?)%>
<%= link_to 'Edit', edit_cart_path(@cart) %> 
<%end%>
<%= link_to 'Back', carts_path %>